In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('./combined_data.csv')

In [3]:
df.drop(['UID','request_id','approved_on','requested_on','Unnamed: 0'],axis=1,inplace=True)

In [4]:
data=df[df['approval_status']=='Approved']

In [5]:
data.drop(['approver'],axis=1,inplace=True)

C:\Users\SaiRamMaganti\AppData\Local\Temp\ipykernel_14224\2905467368.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(['approver'],axis=1,inplace=True)


In [6]:
data.drop(['approval_status'],axis=1,inplace=True)

C:\Users\SaiRamMaganti\AppData\Local\Temp\ipykernel_14224\1481874764.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(['approval_status'],axis=1,inplace=True)


In [7]:
data

application    request_type     request_status  account_name  \
1        Application_0  Modify Account  Approval Complete     account_0   
2       Application_26     New Account  Approval Complete     account_0   
3        Application_0  Modify Account  Approval Complete     account_1   
4        Application_0  Modify Account  Approval Complete    account_10   
5        Application_0  Modify Account  Approval Complete    account_10   
...                ...             ...                ...           ...   
232276  Application_52     New Account  Approval Complete  account_9997   
232277  Application_52     New Account  Approval Complete  account_9998   
232278  Application_52     New Account  Approval Complete  account_9998   
232279  Application_52     New Account  Approval Complete  account_9999   
232280  Application_52     New Account  Approval Complete  account_9999   

          entitlement entitlement_value approval_type employeeType       dept  \
1       entitlement_0         ent_val_0    app_type_2     emType_2  dept_8828   
2       entitlement_2         ent_val_6   app_type_28     emType_2  dept_8828   
3       entitlement_0         ent_val_1    app_type_1     emType_2  dept_9022   
4       entitlement_0         ent_val_3    app_type_2     emType_2  dept_6732   
5       entitlement_0         ent_val_3    app_type_0     emType_2  dept_6732   
...               ...               ...           ...          ...        ...   
232276  entitlement_1       ent_val_745   app_type_36     emType_2  dept_3929   
232277  entitlement_2         ent_val_6   app_type_36     emType_2  dept_8920   
232278  entitlement_1       ent_val_745   app_type_36     emType_2  dept_8920   
232279  entitlement_2         ent_val_6   app_type_36     emType_2  dept_9812   
232280  entitlement_1       ent_val_746   app_type_36     emType_2  dept_9812   

            div hrOrganizationCode  
1        div_60          hrCode_34  
2        div_60          hrCode_34  
3        div_13         hrCode_116  
4       div_387          hrCode_11  
5       div_387          hrCode_11  
...         ...                ...  
232276    div_7          hrCode_24  
232277    div_7         hrCode_455  
232278    div_7         hrCode_455  
232279    div_7          hrCode_89  
232280    div_7          hrCode_89  

[221414 rows x 11 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
for col in data.columns:
    data[col] = encoder.fit_transform(data[col])

C:\Users\SaiRamMaganti\AppData\Local\Temp\ipykernel_14224\1101860288.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[col] = encoder.fit_transform(data[col])


In [9]:
data

application  request_type  request_status  account_name  entitlement  \
1                 0             0               0             0            0   
2               344             1               0             0          109   
3                 0             0               0             1            0   
4                 0             0               0             2            0   
5                 0             0               0             2            0   
...             ...           ...             ...           ...          ...   
232276          618             1               0         28171            1   
232277          618             1               0         28172          109   
232278          618             1               0         28172            1   
232279          618             1               0         28173          109   
232280          618             1               0         28173            1   

        entitlement_value  approval_type  employeeType   dept  div  \
1                       0            111             5  12007  430   
2                   11179            157             5  12007  430   
3                       1              1             5  12224   35   
4                    8129            111             5   9694  320   
5                    8129              0             5   9694  320   
...                   ...            ...           ...    ...  ...   
232276              12628            166             5   6591  440   
232277              11179            166             5  12110  440   
232278              12628            166             5  12110  440   
232279              11179            166             5  13096  440   
232280              12634            166             5  13096  440   

        hrOrganizationCode  
1                      268  
2                      268  
3                       20  
4                       13  
5                       13  
...                    ...  
232276                 157  
232277                 396  
232278                 396  
232279                 559  
232280                 559  

[221414 rows x 11 columns]

In [10]:
features=list(data.columns)[1:]

In [11]:
features

['request_type',
 'request_status',
 'account_name',
 'entitlement',
 'entitlement_value',
 'approval_type',
 'employeeType',
 'dept',
 'div',
 'hrOrganizationCode']

In [54]:
data = data.sample(frac = 1)

In [55]:
mask = np.random.rand(len(data)) <= 0.98

train = data[mask]
test = data[~mask]

In [56]:
print(len(train))
print(len(test))
print(test.shape)

217015
4399
(4399, 11)


In [57]:
x_train=train[features]
y_train=train['application']

x_test=test[features]
y_test=test['application']

In [58]:
len(data['application'].unique())

1091

In [59]:
len(y_train.unique())

1091

In [60]:
from keras.utils import np_utils
dummy_y = np_utils.to_categorical(y_train)

In [61]:
len(dummy_y[0])

1091

In [62]:
from keras.wrappers.scikit_learn import KerasClassifier

from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping

In [63]:
model = Sequential()
model.add(Dense(10, input_shape=(x_train.shape[1],), activation='relu')) # input shape is (features,)
model.add(Dense(16, activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(1091, activation='softmax'))
model.summary()

model.compile(optimizer='Adam', 
              loss='categorical_crossentropy', # this is different instead of binary_crossentropy (for regular classification)
              metrics=['accuracy'])

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                110       
                                                                 
 dense_1 (Dense)             (None, 16)                176       
                                                                 
 dense_2 (Dense)             (None, 16)                272       
                                                                 
 dense_3 (Dense)             (None, 1091)              18547     
                                                                 
Total params: 19,105
Trainable params: 19,105
Non-trainable params: 0
_________________________________________________________________


In [64]:
import keras
from keras.callbacks import EarlyStopping

# early stopping callback
# This callback will stop the training when there is no improvement in  
# the validation loss for 10 consecutive epochs.  
es = keras.callbacks.EarlyStopping(monitor='val_loss', 
                                   mode='min',
                                   patience=10, 
                                   restore_best_weights=True) # important - otherwise you just return the last weigths...

# now we just update our model fit call
history = model.fit(x_train,
                    dummy_y,
                    callbacks=[es],
                    epochs=10, # you can set this to a big number!
                    batch_size=10,
                    shuffle=True,
                    validation_split=0.2,
                    verbose=1)

Epoch 1/10
17362/17362 [==============================] - 67s 4ms/step - loss: 5.4490 - accuracy: 0.1113 - val_loss: 4.5064 - val_accuracy: 0.1110
Epoch 2/10
17362/17362 [==============================] - 63s 4ms/step - loss: 4.5036 - accuracy: 0.1115 - val_loss: 4.5112 - val_accuracy: 0.1110
Epoch 3/10
17362/17362 [==============================] - 63s 4ms/step - loss: 4.5068 - accuracy: 0.1115 - val_loss: 4.5170 - val_accuracy: 0.1110
Epoch 4/10
17362/17362 [==============================] - 67s 4ms/step - loss: 4.5096 - accuracy: 0.1115 - val_loss: 4.5204 - val_accuracy: 0.1110
Epoch 5/10
17362/17362 [==============================] - 66s 4ms/step - loss: 4.5117 - accuracy: 0.1115 - val_loss: 4.5224 - val_accuracy: 0.1110
Epoch 6/10
17362/17362 [==============================] - 58s 3ms/step - loss: 4.5132 - accuracy: 0.1115 - val_loss: 4.5239 - val_accuracy: 0.1110
Epoch 7/10
17362/17362 [==============================] - 56s 3ms/step - loss: 4.5142 - accuracy: 0.1115 - val_loss: 4

In [67]:
preds = model.predict(x_test) # see how the model did!
print(preds[0]) # i'm spreading that prediction across three nodes and they sum to 1
print(np.sum(preds[0]))

138/138 [==============================] - 1s 3ms/step
[2.0055561e-03 1.2678732e-04 6.1541374e-07 ... 2.1243935e-08 1.3079557e-07
 1.1066810e-05]
0.9999999


In [81]:
ar=sorted(preds[0],reverse=True)[:5]
print(ar)
for i in ar:
    print(np.where(preds[0]==i))

[0.11101282, 0.08446016, 0.07133432, 0.06307219, 0.031299066]
(array([488], dtype=int64),)
(array([126], dtype=int64),)
(array([595], dtype=int64),)
(array([955], dtype=int64),)
(array([507], dtype=int64),)


In [76]:
y_test

77879     413
62067     364
69721     595
149685    598
40824     325
         ... 
166187    955
112377    360
216440    198
37233     277
226244    506
Name: application, Length: 4399, dtype: int32